### ISSUE TITLE
Is there recommend?

### ISSUE THREAD

**Issue by sam-choi** [songgc/TF-recomm#2]
When I checked TF-recomm, I couldn't find out recommend api.
As you know, movie recommend engine can recommend movie like crab recommender.

>>> #Recommend items for the user 5 (Toby)
>>> recommender.recommend(5)
[(5, 3.3477895267131013), (1, 2.8572508984333034), (6, 2.4473604699719846)]

Is there any recommend api like above example?

**Comment by songgc** [comment]
The purpose of this repo is to inspire people that you can apply Tensorflow to non-deep learning problems and use a unified framework to solve various projects. Therefore, the repo only focuses on the core ML parts rather than serving parts. In my option, it wouldn't be hard to extend the core algorithm to better serving APIs. However, this is not in my top interests.
