### ISSUE TITLE
big number of users

### ISSUE THREAD

**Issue by pianoman4873** [songgc/TF-recomm#4]
Hello, 
What happens when the number of users is very large ( e.g. 1 billion ) - 
The embedding matrix would be gigantic.
This seems unfeasible - or am I wrong ?

Thanks

**Comment by songgc** [comment]
The byte size of the user embedding matrix can be calculated by USER_NUM * DIM * 4. Assume that USER_NUM=1G, DIM=15, and then 60GB is required, which seems not super large although I'm not sure if you can train it in a computer with 128GB RAM. You could train it over multiple computers. however, model parallelism is non-trivial for sure. 

As for me, I would try reducing the space of tail users since the active users usually are only 0.1-5% of the total. Several approaches I would try are
-- Remove tail users with a certain cutoff
-- Do hashing trick for tail users
-- Petition tail users by certain rules and reduce user space per petition accordingly  

With my experience, you could reduce the RAM consumption to only 1/10 ~ 1/100 with no noticeable  performance loss.

**Comment by pianoman4873** [comment]
OK, thanks. 
And suppose instead of items for recommendation , the columns are actually 
various  categorical ( could also be multiple choice )/ numerical / boolean answers of the users on various questions (regarding various preferences / behaviors of the users - for example - do you have doc  ? Which genres of music do you love listening to  ? how would you rate  etc. ) . The matrix is sparsely populated and I would like to predict missing entries. Do you think that could work as well for this domain  ( of course with proper feature manipulation ), or would you solve the above with a different ML technique ?

**Comment by songgc** [comment]
Please look at [Google's paper](https://research.google.com/pubs/pub45530.html)

**Comment by pianoman4873** [comment]
thanks
